name: Build and Release

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ['16']
    
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }} with Node ${{ matrix.node_version }}
    steps:
      - name: Checkout current commit/branch/tag
        uses: actions/checkout@v2

      - name: Setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: yarn install

      - name: Bundle files
        run: yarn bundle
        env:
          NODE_ENV: production

      - name: Publish new release
        run: yarn release
        env:
          CI: true
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
